question_data = [
    {"text": "A slug's blood is green.", "answer": True},
    {"text": "The loudest animal is the African Elephant.", "answer": False},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": True},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": True},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car,"
             "you are free to take it home to eat.", "answer": True},
    {"text": "In London, UK, if you happen to die in the House of Parliament,"
             "you are entitled to a state funeral.", "answer": False},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": True},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": False},
    {"text": "Google was originally called 'Backrub'.", "answer": True},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": True},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": False},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": True}
]


# data from https://opentdb.com/api.php?amount=50&type=boolean
new_data = [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
             "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a "
                         "joystick in a Saab 9000.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
             "question": "The Doppler effect applies to light.", "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "History", "type": "boolean", "difficulty": "easy",
             "question": "The Cold War ended with Joseph Stalin&#039;s death.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 "
                         "billion in stock.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "History", "type": "boolean", "difficulty": "easy",
             "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "Gumbo is a stew that originated in Louisiana.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Geography", "type": "boolean", "difficulty": "easy",
             "question": "San Marino is the only country completely surrounded by another country.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "easy",
             "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Politics", "type": "boolean", "difficulty": "easy",
             "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US "
                         "presidential elections.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
             "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "History", "type": "boolean", "difficulty": "medium",
             "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say "
                         "it&quot; is a quote from French philosopher Voltaire.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Music", "type": "boolean",
             "difficulty": "medium",
             "question": "The country song  &ldquo;A Boy Named Sue&rdquo; was written by Shel Silverstein.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
             "question": "The book 1984 was published in 1949.", "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "Nutella is produced by the German company Ferrero.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "hard",
             "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat "
                         "mode in Half Moon style.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
             "question": "Type 1 diabetes is a result of the liver working improperly.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "easy",
             "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Geography", "type": "boolean", "difficulty": "medium",
             "question": "Vietnam is the only country in the world that starts with V. ",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "medium",
             "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Art", "type": "boolean", "difficulty": "medium",
             "question": "Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
             "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, "
                         "a mollusc, known to be aged as 507 years old.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Geography", "type": "boolean", "difficulty": "easy",
             "question": "Toronto is the capital city of the North American country of Canada.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Geography", "type": "boolean", "difficulty": "easy",
             "question": "St. Louis is the capital of the US State Missouri.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Geography", "type": "boolean", "difficulty": "medium",
             "question": "Antarctica is the largest desert in the world.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Sports", "type": "boolean", "difficulty": "medium",
             "question": "The Olympics tennis court is a giant green screen.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Board Games", "type": "boolean",
             "difficulty": "easy",
             "question": "There is a Donald Trump Board Game, which was made in 1989.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Animals", "type": "boolean", "difficulty": "medium",
             "question": "The Platypus is a mammal.", "correct_answer": "True",
             "incorrect_answers": ["False"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "When you cry in space, your tears stick to your face.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed "
                         "Darth Vader.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall "
                         "between the United States and Mexico.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "easy",
             "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
             "question": "Ferrari has never made a V10 engine for any of its cars.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "easy",
             "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
             "question": "The first dual-core CPU was the Intel Pentium D.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "medium",
             "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The "
                         "Reckoning&quot;.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Politics", "type": "boolean", "difficulty": "medium",
             "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Video Games", "type": "boolean",
             "difficulty": "easy",
             "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead "
                         "to curse the enemy team.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Television", "type": "boolean",
             "difficulty": "easy",
             "question": "Klingons express emotion in art through opera and poetry.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Television", "type": "boolean",
             "difficulty": "easy",
             "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
             "question": "The sum of any two odd integers is odd.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "The National Animal of Scotland is the Unicorn.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
             "difficulty": "hard",
             "question": "In the &quot;Kagerou Daze&quot; series, Shintaro Kisaragi is prominently shown with the "
                         "color red.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "History", "type": "boolean", "difficulty": "easy",
             "question": "The United States of America was the first country to launch a man into space.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
             "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
             "question": "A scalene triangle has two sides of equal length.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "History", "type": "boolean", "difficulty": "medium",
             "question": "The Korean War ended in 1953 without any ceasefire.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
             "question": "A pasodoble is a type of Italian pasta sauce.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Sports", "type": "boolean", "difficulty": "medium",
             "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce "
                         "injuries.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "History", "type": "boolean", "difficulty": "medium",
             "question": "Franz Joseph I was the last emperor of Austria.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
             "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The "
                         "Lord of The Rings&quot;.",
             "correct_answer": "False", "incorrect_answers": ["True"]}]
